language: ruby

rvm:
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.0.1.0

gemfile:
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile

cache: bundler

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
